name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image
        run: docker build -t cygwin64:latest .
